start_comment: |
    "       __        __      __                       __   ___  __  "
    " |    /  \  /\  |  \    |__)  /\  |     /\  |\ | /  ` |__  |__) "
    " |___ \__/ /~~\ |__/    |__) /~~\ |___ /~~\ | \| \__, |___ |  \ "